import { FormEvent, useCallback, useEffect, useState } from "react";
import { apiFetch, apiList, formatDate, jsonBody, shortId } from "../lib/api";
import type { CollectionRecord, NotificationPreferences } from "../lib/types";
import { Badge, EmptyState, ErrorState, LoadingState, PageHeader, SectionCard } from "../components/ViewPrimitives";
import { PwaStatus } from "../components/PwaStatus";
import { WatchManagementView } from "./WatchManagementView";

export function CollectionView({ kind }: { kind: "topics" | "subjects" | "sources" }) {
  const [items, setItems] = useState<CollectionRecord[]>([]); const [suggestions, setSuggestions] = useState<CollectionRecord[]>([]); const [error, setError] = useState<unknown>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setItems((await apiList<CollectionRecord>(`/${kind}?page_size=100`)).items); if (kind === "sources") setSuggestions((await apiFetch<{ items: CollectionRecord[] }>("/source-suggestions?status=pending")).items); } catch (caught) { setError(caught); } finally { setLoading(false); } }, [kind]); useEffect(() => { void load(); }, [load]);
  async function reviewSuggestion(id: string, status: "approved" | "rejected") { try { await apiFetch(`/source-suggestions/${id}/review`, { method: "POST", body: jsonBody({ status }) }); setSuggestions((list) => list.filter((item) => item.id !== id)); } catch (caught) { setError(caught); } }
  const labels = { topics: ["Configure", "Topics", "Approved vocabulary and scope suggestions."], subjects: ["Configure", "Subjects", "Canonical entities that give monitoring and Story context."], sources: ["Configure", "Sources", "Origins, acquisition profiles, and explicitly reviewed source suggestions."] }[kind];
  if (loading) return <><PageHeader eyebrow={labels[0]} title={labels[1]} description={labels[2]} /><LoadingState />{error && <ErrorState error={error} />}</>;
  return <><PageHeader eyebrow={labels[0]} title={labels[1]} description={labels[2]} />{error && <ErrorState error={error} retry={() => void load()} />}<SectionCard title={`Active ${kind}`} description="Canonical API state; soft-deleted records are excluded by default.">{items.length ? <div className="table-wrap"><table><thead><tr><th scope="col">Name</th><th scope="col">Type</th><th scope="col">Identifier</th><th scope="col">State</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{String(item.name ?? item.title ?? item.canonical_name ?? "Unnamed")}</strong></td><td>{String(item.subject_type ?? item.source_kind ?? item.priority ?? "—")}</td><td><code>{shortId(item.id)}</code></td><td><Badge tone={item.enabled === false ? "neutral" : "mint"}>{item.enabled === false ? "disabled" : "active"}</Badge></td></tr>)}</tbody></table></div> : <EmptyState title={`No ${kind}`} description="Create the first canonical record through the API-backed workflow." />}</SectionCard>{kind === "sources" && <SectionCard title="Source approval queue" description="Suggestions stay inert until an explicit review decision.">{suggestions.length ? <div className="resource-list">{suggestions.map((item) => <div className="resource-row" key={item.id}><span><strong>{String(item.name ?? "Source suggestion")}</strong><small>{String(item.rationale ?? item.likely_contribution ?? "No rationale recorded")}</small></span><div className="button-row"><button className="secondary-button" type="button" onClick={() => void reviewSuggestion(item.id, "approved")}>Approve</button><button className="quiet-button" type="button" onClick={() => void reviewSuggestion(item.id, "rejected")}>Reject</button></div></div>)}</div> : <EmptyState title="Queue is clear" description="No pending source suggestions need review." />}</SectionCard>}</>;
}

export function MonitorsView() {
  return <WatchManagementView />;
}

export function QuestionsView() {
  const [items, setItems] = useState<CollectionRecord[]>([]); const [question, setQuestion] = useState(""); const [error, setError] = useState<unknown>(null); const [working, setWorking] = useState(false); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setItems((await apiList<CollectionRecord>("/research-questions?page_size=100")).items); } catch (caught) { setError(caught); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent) { event.preventDefault(); if (!question.trim()) return; setWorking(true); try { const item = await apiFetch<CollectionRecord>("/research-questions", { method: "POST", body: jsonBody({ question, origin_type: "user", priority: "normal", search_attempt_budget: 3, query_budget: 10, local_model_budget: 10, paid_budget_usd: 0 }) }); setItems((list) => [item, ...list]); setQuestion(""); } catch (caught) { setError(caught); } finally { setWorking(false); } }
  if (loading) return <><PageHeader eyebrow="Configure" title="Research questions" description="Turn uncertainty into bounded, reviewable work." /><LoadingState />{error && <ErrorState error={error} />}</>;
  return <><PageHeader eyebrow="Configure / gaps" title="Research questions" description="Open questions, evidence links, attempt budgets, hypotheses, and follow-up Jobs remain inspectable." />{error && <ErrorState error={error} retry={() => void load()} />}<SectionCard title="Ask a bounded question"><form className="inline-form" onSubmit={create}><label htmlFor="question">Question</label><input id="question" name="question" autoComplete="off" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="What evidence would change this Story?" /><button className="primary-button" type="submit" disabled={working}>Add question</button></form></SectionCard><SectionCard title="Open questions" description="Questions do not silently create Claims or recursive research loops.">{items.length ? <div className="resource-list">{items.map((item) => <div className="resource-row" key={item.id}><span><strong>{String(item.question)}</strong><small>{String(item.priority ?? "normal")} priority · {shortId(item.id)}</small></span><Badge tone={item.status === "open" ? "amber" : "mint"}>{String(item.status ?? "open")}</Badge></div>)}</div> : <EmptyState title="No open questions" description="Create a question when a Story needs a deliberate evidence gap." />}</SectionCard></>;
}

export function RunsView() {
  const [runs, setRuns] = useState<CollectionRecord[]>([]); const [jobs, setJobs] = useState<CollectionRecord[]>([]); const [error, setError] = useState<unknown>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const [runResult, jobResult] = await Promise.all([apiList<CollectionRecord>("/runs?page_size=100"), apiList<CollectionRecord>("/jobs?page_size=100")]); setRuns(runResult.items); setJobs(jobResult.items); } catch (caught) { setError(caught); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  if (loading) return <><PageHeader eyebrow="Operate" title="Runs & jobs" description="Durable work, attempts, leases, budgets, and outcomes." /><LoadingState />{error && <ErrorState error={error} />}</>;
  return <><PageHeader eyebrow="Operate / durability" title="Runs & jobs" description="Restart-safe execution state, retries, cancellation, and cost boundaries." />{error && <ErrorState error={error} retry={() => void load()} />}<div className="content-grid"><SectionCard title="Recent runs">{runs.length ? <div className="resource-list">{runs.map((run) => <div className="resource-row" key={run.id}><span><strong>{String(run.trigger_type ?? "run")}</strong><small>{formatDate(String(run.started_at ?? ""))} · {shortId(run.id)}</small></span><Badge tone={run.status === "success" ? "mint" : run.status === "failed" ? "coral" : "amber"}>{String(run.status ?? "running")}</Badge></div>)}</div> : <EmptyState title="No runs" description="Scheduler and manual runs will appear here." />}</SectionCard><SectionCard title="Queued and completed jobs">{jobs.length ? <div className="table-wrap"><table><thead><tr><th scope="col">Job</th><th scope="col">Type</th><th scope="col">Attempts</th><th scope="col">State</th></tr></thead><tbody>{jobs.map((job) => <tr key={job.id}><td><code>{shortId(job.id)}</code></td><td>{String(job.job_type ?? "—")}</td><td>{String(job.attempts ?? 0)} / {String(job.max_attempts ?? 0)}</td><td><Badge tone={job.status === "succeeded" ? "mint" : job.status === "failed" ? "coral" : "amber"}>{String(job.status)}</Badge></td></tr>)}</tbody></table></div> : <EmptyState title="No jobs" description="Durable Jobs will appear here when a Monitor or Question pursues work." />}</SectionCard></div></>;
}

export function SettingsView() {
  const [settings, setSettings] = useState<CollectionRecord[]>([]); const [budgets, setBudgets] = useState<CollectionRecord[]>([]); const [preferences, setPreferences] = useState<NotificationPreferences | null>(null); const [error, setError] = useState<unknown>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const [settingResult, budgetResult, preferenceResult] = await Promise.all([apiList<CollectionRecord>("/settings?page_size=100"), apiFetch<{ items: CollectionRecord[] }>("/budgets/limits"), apiFetch<NotificationPreferences>("/notification-preferences")]); setSettings(settingResult.items); setBudgets(budgetResult.items); setPreferences(preferenceResult); } catch (caught) { setError(caught); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  async function setBrowser(enabled: boolean) { setSaving(true); try { const permission = enabled && "Notification" in window ? await Notification.requestPermission() : "default"; setPreferences(await apiFetch<NotificationPreferences>("/notification-preferences", { method: "PUT", body: jsonBody({ browser_enabled: enabled && permission === "granted", permission_state: permission, online: navigator.onLine }) })); } catch (caught) { setError(caught); } finally { setSaving(false); } }
  if (loading) return <><PageHeader eyebrow="Operate" title="Settings & cost" description="Runtime preferences, browser delivery, provider usage, and budgets." /><LoadingState />{error && <ErrorState error={error} />}</>;
  return <><PageHeader eyebrow="Operate / local control" title="Settings & cost" description="The app is local-first, paid escalation is explicit, and browser notifications are opt-in." />{error && <ErrorState error={error} retry={() => void load()} />}<div className="content-grid"><SectionCard title="App install"><p className="muted">Install the responsive workspace for quicker review and a dedicated window.</p><PwaStatus /></SectionCard><SectionCard title="Browser notifications"><p className="muted">In-app alerts remain authoritative. Browser delivery is optional and records permission or offline state.</p><button className="secondary-button" type="button" onClick={() => void setBrowser(!(preferences?.browser_enabled ?? false))} disabled={saving}>{preferences?.browser_enabled ? "Disable browser notifications" : "Enable browser notifications"}</button><p className="status-note">Permission: {preferences?.permission_state ?? "unknown"} · Network: {preferences?.online ? "online" : "offline"}</p></SectionCard></div><SectionCard title="Budget limits" description="Configured server-side limits and paid routing state.">{budgets.length ? <div className="resource-list">{budgets.map((budget) => <div className="resource-row" key={budget.id}><span><strong>{String(budget.scope_type ?? "budget")}</strong><small>{String(budget.scope_id ?? "global")}</small></span><code>{JSON.stringify(budget)}</code></div>)}</div> : <EmptyState title="No budget limits" description="The default local-first path is active." />}</SectionCard><SectionCard title="Settings"><div className="resource-list">{settings.length ? settings.map((setting) => <div className="resource-row" key={setting.id}><span><strong>{String(setting.key ?? setting.name ?? setting.id)}</strong></span><code>{String(setting.value ?? "")}</code></div>) : <EmptyState title="No custom settings" description="Runtime defaults are in effect." />}</div></SectionCard></>;
}
