import { FormEvent, useCallback, useEffect, useState } from "react";
import { apiFetch, apiList, formatDate, jsonBody } from "../lib/api";
import type { Alert, AlertRule, NotificationPreferences } from "../lib/types";
import { Badge, EmptyState, ErrorState, LoadingState, PageHeader, SectionCard } from "../components/ViewPrimitives";

const EVENT_TYPES = ["new_primary_evidence", "contradiction", "correction", "corroboration", "material_update"];
const label = (value: string) => value.split("_").join(" ");

export function AlertsView() {
  const [alerts, setAlerts] = useState<Alert[]>([]); const [rules, setRules] = useState<AlertRule[]>([]); const [preferences, setPreferences] = useState<NotificationPreferences | null>(null); const [ruleName, setRuleName] = useState(""); const [eventType, setEventType] = useState("material_update"); const [working, setWorking] = useState(false); const [error, setError] = useState<unknown>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [a, r, p] = await Promise.all([apiList<Alert>("/alerts?page_size=100"), apiFetch<{ items: AlertRule[] }>("/alert-rules"), apiFetch<NotificationPreferences>("/notification-preferences")]); setAlerts(a.items); setRules(r.items); setPreferences(p); } catch (caught) { setError(caught); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function acknowledge(id: string) { try { const updated = await apiFetch<Alert>(`/alerts/${id}/acknowledge`, { method: "POST" }); setAlerts((items) => items.map((item) => item.id === id ? updated : item)); } catch (caught) { setError(caught); } }
  async function requestPermission() { setWorking(true); try { const permission = "Notification" in window ? await Notification.requestPermission() : "denied"; const updated = await apiFetch<NotificationPreferences>("/notification-preferences", { method: "PUT", body: jsonBody({ browser_enabled: permission === "granted", permission_state: permission, online: navigator.onLine }) }); setPreferences(updated); } catch (caught) { setError(caught); } finally { setWorking(false); } }
  async function createRule(event: FormEvent) { event.preventDefault(); if (!ruleName.trim()) return; setWorking(true); try { const rule = await apiFetch<AlertRule>("/alert-rules", { method: "POST", body: jsonBody({ name: ruleName, target_type: "all", event_types: [eventType], min_importance: .5, browser_enabled: preferences?.permission_state === "granted" }) }); setRules((items) => [...items, rule]); setRuleName(""); } catch (caught) { setError(caught); } finally { setWorking(false); } }
  if (loading) return <><PageHeader eyebrow="Operate" title="Alerts" description="Durable attention state with optional browser delivery." /><LoadingState />{error && <ErrorState error={error} />}</>;
  return <><PageHeader eyebrow="Operate / durable state" title="Alerts" description="A browser permission decision never removes the authoritative in-app alert." action={preferences?.permission_state !== "granted" ? <button className="primary-button" type="button" onClick={() => void requestPermission()} disabled={working}>{working ? "Requesting…" : "Enable browser notifications"}</button> : <Badge tone="mint">Browser notifications enabled</Badge>} />{error && <ErrorState error={error} retry={() => void load()} />}<div className="content-grid alerts-grid"><SectionCard title="Needs attention" description={`${alerts.filter((alert) => alert.status === "unread").length} unread alert(s)`}>{alerts.length ? <div className="alert-list">{alerts.map((alert) => <article className={`alert-detail-row ${alert.status}`} key={alert.id}><div><div className="button-row"><Badge tone={alert.event_type === "contradiction" || alert.event_type === "correction" ? "coral" : "amber"}>{label(alert.event_type)}</Badge><span>{alert.importance_score.toFixed(2)} importance</span></div><h3>{alert.title}</h3><p>{alert.body}</p><small>{formatDate(alert.created_at)} · {alert.deliveries.map((delivery) => `${delivery.channel}: ${delivery.status}`).join(" · ")}</small></div>{alert.status === "unread" && <button className="secondary-button" type="button" onClick={() => void acknowledge(alert.id)}>Acknowledge</button>}</article>)}</div> : <EmptyState title="No alerts" description="Material changes will appear here when a rule matches." />}</SectionCard><SectionCard title="Create a rule" description="Rules match material report causes, never raw keyword or article volume."><form className="stack-form" onSubmit={createRule}><label htmlFor="rule-name">Rule name</label><input id="rule-name" name="rule_name" autoComplete="off" value={ruleName} onChange={(event) => setRuleName(event.target.value)} placeholder="Primary changes" /><label htmlFor="rule-event">Material event</label><select id="rule-event" name="event_type" value={eventType} onChange={(event) => setEventType(event.target.value)}>{EVENT_TYPES.map((event) => <option value={event} key={event}>{label(event)}</option>)}</select><button className="primary-button" type="submit" disabled={working}>Save rule</button></form><div className="rule-list">{rules.map((rule) => <div className="rule-row" key={rule.id}><span><strong>{rule.name}</strong><small>{rule.target_type} · {rule.event_types.join(", ") || "all material events"}</small></span><Badge tone={rule.enabled ? "mint" : "neutral"}>{rule.enabled ? "enabled" : "paused"}</Badge></div>)}</div></SectionCard></div></>;
}
