import { FormEvent, useCallback, useEffect, useState } from "react";
import { apiFetch, apiList, formatDate, jsonBody, shortId } from "../lib/api";
import type { Alert, Report, Story } from "../lib/types";
import { Badge, EmptyState, ErrorState, LoadingState, PageHeader, SectionCard } from "../components/ViewPrimitives";

export function SavedView() {
  const [storyId, setStoryId] = useState(""); const [story, setStory] = useState<Story & { review?: { review_status: string; new_update: boolean } } | null>(null); const [error, setError] = useState<unknown>(null); const [loading, setLoading] = useState(false);
  async function load(event: FormEvent) { event.preventDefault(); if (!storyId.trim()) return; setLoading(true); setError(null); try { setStory(await apiFetch(`/stories/${encodeURIComponent(storyId.trim())}`)); } catch (caught) { setError(caught); } finally { setLoading(false); } }
  async function setReview(status: "saved" | "dismissed" | "not_useful") { if (!story) return; try { const updated = await apiFetch<Story & { review?: { review_status: string; new_update: boolean } }>(`/stories/${story.id}/review`, { method: "POST", body: jsonBody({ review_status: status }) }); setStory(updated); } catch (caught) { setError(caught); } }
  const headline = story?.current_revision?.headline ?? story?.headline ?? "Story";
  const summary = story?.current_revision?.summary ?? story?.summary ?? "No summary recorded.";
  return <><PageHeader eyebrow="Review / attention" title="Saved" description="Review attention is separate from Story evolution; a new update never destroys a saved decision." /><SectionCard title="Open saved review state"><form className="inline-form" onSubmit={load}><label htmlFor="saved-story-id">Story ID</label><input id="saved-story-id" name="story_id" autoComplete="off" value={storyId} onChange={(event) => setStoryId(event.target.value)} placeholder="st_…" /><button className="primary-button" type="submit" disabled={loading}>{loading ? "Loading…" : "Open Story"}</button></form></SectionCard>{error && <ErrorState error={error} />}{loading && <LoadingState />}{story ? <SectionCard title={headline} description={summary}><div className="button-row"><Badge tone={story.review?.review_status === "saved" ? "mint" : "neutral"}>{story.review?.review_status ?? "new"}</Badge>{story.review?.new_update && <Badge tone="coral">new update</Badge>}<button className="secondary-button" type="button" onClick={() => void setReview("saved")}>Save</button><button className="quiet-button" type="button" onClick={() => void setReview("dismissed")}>Dismiss</button><button className="quiet-button" type="button" onClick={() => void setReview("not_useful")}>Not useful</button></div></SectionCard> : <EmptyState title="Choose a Story" description="Open a Story ID to inspect and change its review attention without rewriting evidence." />}</>;
}

export function HistoryView() {
  const [alerts, setAlerts] = useState<Alert[]>([]); const [reports, setReports] = useState<Report[]>([]); const [error, setError] = useState<unknown>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const [alertResult, reportResult] = await Promise.all([apiList<Alert>("/alerts?status=acknowledged&page_size=100"), apiList<Report>("/reports?page_size=100")]); setAlerts(alertResult.items); setReports(reportResult.items); } catch (caught) { setError(caught); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  if (loading) return <><PageHeader eyebrow="Review" title="History" description="Acknowledgements, report revisions, and durable decisions." /><LoadingState />{error && <ErrorState error={error} />}</>;
  return <><PageHeader eyebrow="Review / audit trail" title="History" description="A compact view of decisions already made and revisions that remain inspectable." />{error && <ErrorState error={error} retry={() => void load()} />}<div className="content-grid"><SectionCard title="Acknowledged alerts">{alerts.length ? <div className="resource-list">{alerts.map((alert) => <div className="resource-row" key={alert.id}><span><strong>{alert.title}</strong><small>{formatDate(alert.created_at)} · {shortId(alert.id)}</small></span><Badge tone="mint">acknowledged</Badge></div>)}</div> : <EmptyState title="No acknowledged alerts" description="Acknowledged material changes will remain available here." />}</SectionCard><SectionCard title="Report revision trails">{reports.length ? <div className="resource-list">{reports.map((report) => <div className="resource-row" key={report.id}><span><strong>{report.name}</strong><small>{report.current_revision_id ? "Current revision available" : "No revision yet"} · {report.target_type}</small></span><Badge tone="neutral">immutable</Badge></div>)}</div> : <EmptyState title="No report history" description="Generated Living Report revisions will appear here." />}</SectionCard></div></>;
}
